### PR TITLE
Test safe-cli against phase-2b vaults

### PR DESCRIPTION
**Pull request by ravinderjangra**

### CODE REVIEW

**Comment by bochaco** [comment]
I think we need to still keep test with baby fleming disabled, the problem will be solved once we have CRDT hopefully

**Comment by ravinderjangra** [comment]
I think we are fine with disabling the tests though don't we want to ensure the cli and APIs are working fine with the latest vaults? Because I noticed some test failures.

**Comment by bochaco** [comment]
L which wasn't solved yet, and we hope they will be solved with crdt changes

**Comment by ravinderjangra** [comment]
I think, we will have to disable the benchmarks as well since I have updated the `safe-nlt` dependency.

**Comment by bochaco** [comment]
yeah, it seems so

**Comment by bochaco** [comment]
I kept the benchmark running with your vault @ravinderjangra for now, and disabled only the fleming tests.

**Pull request merged**
